language: csharp
mono:
  - latest
install:
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - echo '#!/bin/bash' > ./xcopy
  - echo "string2='/*'" >> ./xcopy
  - echo 'cp -r $1$string2 $2' >> ./xcopy
  - sudo chmod '+x' ./xcopy
  - sudo mv ./xcopy /bin
  - msbuild /p:Configuration=Release CLI/CLI.csproj
  - msbuild /p:Configuration=Release Engine.Tests/Engine.Tests.csproj
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Engine.Tests/bin/Release/NaturalDocs.Engine.Tests.dll
