language: csharp
mono:
  - latest
install:
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - echo '#!/bin/bash' > ./xcopy
  - echo 'cp -r $1 $2' >> ./xcopy
  - sudo chmod 777 ./xcopy
  - sudo mv ./xcopy /bin
  - msbuild /p:Configuration=Release CLI/CLI.csproj
  - msbuild /p:Configuration=Release Engine.Tests.Runner/Engine.Tests.Runner.csproj
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Engine.Tests.Runner/bin/Release/nunit.framework.dll
