language: csharp
mono:
  - latest
script:
  - echo '#!/bin/bash' > ./xcopy
  - echo 'cp -r $1 $2' >> ./xcopy
  - sudo chmod 777 ./xcopy
  - sudo mv ./xcopy /bin
  - msbuild /p:Configuration=Release CLI/CLI.csproj
