language: csharp
mono:
  - latest
dotnet: 2.1.502
install:
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
  - dotnet tool install --global coverlet.console
  - dotnet add package coverlet.msbuild
script:
  - echo '#!/bin/bash' > ./xcopy
  - echo 'cp -r $1 $2' >> ./xcopy
  - sudo chmod 777 ./xcopy
  - sudo mv ./xcopy /bin
  - msbuild /p:Configuration=Release CLI/CLI.csproj
  - msbuild /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=opencover.xml /p:Configuration=Release Engine.Tests/Engine.Tests.csproj
  - cp -r Engine/Resources/Translations Engine.Tests/bin/Release/
  - cp -r Engine/Resources/Config Engine.Tests/bin/Release/
  - cp -r Engine/Resources/Styles Engine.Tests/bin/Release/
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Engine.Tests/bin/Release/NaturalDocs.Engine.Tests.dll
after_script:
  - curl -F 'xml_file=opencover.xml' "https://coveralls.io/api/v1/jobs"
