version: 0.0.{build}
image: 
  - Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
 matrix: 
      - NaturalDocs: CLI/CLI.csproj 
      - NaturalDocs: Engine.Tests/Engine.Tests.csproj
build:
  project: $(NaturalDocs)
test:
  assemblies:
    - ./Engine.Tests/bin/Release/NaturalDocs.Engine.Tests.dll
