version: 0.0.{build}
image: 
  - Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: Engine.Tests/Engine.Tests.csproj
test:
  assemblies:
    - ./Engine.Tests/bin/Release/NaturalDocs.Engine.Tests.dll
