version: 0.0.{build}
image: 
  - Visual Studio 2017
environment:
  matrix:
    - NaturalDocsProj: Engine.Tests/Engine.Tests.csproj
    - NaturalDocsProj: CLI/CLI.csproj
before_build:
  - nuget restore $(NaturalDocsProj)
  - choco install opencover.portable
  - choco install codecov
build:
  project: $(NaturalDocsProj)
test:
  assemblies:
    - ./Engine.Tests/bin/Debug/NaturalDocs.Engine.Tests.dll
